language: java
jdk: 
  - oraclejdk12
 
services:
  - postgresql

before_script: 
  - chmod +x mvnw
  - psql -c "CREATE DATABASE db_sapef_teste;" -U postgres
  - psql -c "CREATE USER postgres WITH PASSWORD '123456';" -U postgres
